core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

users:
    type:     rest
    resource: AppBundle\Controller\Api\UserController    

invitations:
    type:     rest
    resource: AppBundle\Controller\Api\InvitationController  