<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'core.service.shared.tools' shared service.

include_once $this->targetDirs[3].'/src/CoreBundle/Service/Shared/ToolsService.php';

return $this->services['core.service.shared.tools'] = new \CoreBundle\Service\Shared\ToolsService();
