<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'core.service.user' shared service.

include_once $this->targetDirs[3].'/src/CoreBundle/Service/UserService.php';
include_once $this->targetDirs[3].'/src/CoreBundle/Service/Shared/ToolsService.php';

return $this->services['core.service.user'] = new \CoreBundle\Service\UserService(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['core.service.shared.tools']) ? $this->services['core.service.shared.tools'] : ($this->services['core.service.shared.tools'] = new \CoreBundle\Service\Shared\ToolsService())) && false ?: '_'});
