<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHs6xww7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHs6xww7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHs6xww7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHs6xww7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHs6xww7\appDevDebugProjectContainer([
    'container.build_hash' => 'Hs6xww7',
    'container.build_id' => '72ea2e99',
    'container.build_time' => 1647208078,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHs6xww7');
